// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";
// import Header from "./Header";
// import MainContent from "./MainContent";

// const App = () => {
//   return (
//     <>
//       <Header />
//       <MainContent />
//       <style jsx>{`
//         builder-component {
//           max-width: none !important;
//         }
//       `}</style>
//     </>
//   );
// };

// export default App;
