/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FeatureSection = ({
  title,
  description,
  imageSrc,
  imageAlt,
  reverse = false,
}) => {
  const textContent = (
    <div
      className={`flex flex-col ${
        reverse ? "ml-5 w-[68%]" : "w-[71%]"
      } max-md:ml-0 max-md:w-full`}
    >
      <div className="flex flex-col mt-16 text-black max-md:mt-10 max-md:max-w-full">
        <h2 className="self-start text-5xl font-bold max-md:max-w-full max-md:text-4xl">
          {title}
          <br />
          <br />
        </h2>
        <p className="mt-7 text-3xl max-md:max-w-80%">{description}</p>
      </div>
    </div>
  );

  const imageContent = (
    <div
      className={`flex flex-col ${
        reverse ? "w-[32%]" : "ml-5 w-[29%]"
      } max-md:ml-0 max-md:w-full`}
    >
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-contain grow w-full aspect-[1.06] max-md:mt-10"
      />
    </div>
  );

  return (
    <section
      className={`self-center mt-24 max-w-full w-[1221px] max-md:mt-10 ${
        reverse ? "self-end" : ""
      }`}
    >
      <div className="flex gap-5 max-md:flex-col">
        {reverse ? imageContent : textContent}
        {reverse ? textContent : imageContent}
      </div>
    </section>
  );
};

export default FeatureSection;
