/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero = () => {
  return (
    <section className="flex flex-col self-center mt-40 w-full max-w-[1308px] max-md:mt-10 max-md:max-w-full">
      <div className="max-w-full w-[1274px]">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[57%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col text-black max-md:mt-10 max-md:max-w-full">
              <h1 className="text-6xl max-md:mr-1.5 max-md:max-w-full max-md:text-4xl">
                A <span className="text-7xl font-bold">SMARTER</span> SMART
                CALENDAR
              </h1>
              <p className="mt-14 text-4xl max-md:mt-10 max-md:max-w-full">
                The first scheduler to optimize your life with live health
                insights, long term goals, and lifestyle priorities
              </p>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[43%] max-md:ml-0 max-md:w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/59931d5c4793d14d395c48eca8379ebe39719e6e07297c3c0243183ec11fae07?placeholderIfAbsent=true&apiKey=be7d969155c74017b8611192d433b602"
              alt="Smart Calendar Illustration"
              className="object-contain grow w-full aspect-[1.38] max-md:mt-10 max-md:max-w-full"
            />
          </div>
        </div>
      </div>
      <a
        href="#"
        className="overflow-hidden gap-2 self-start px-3 py-1 mt-3.5 ml-3.5 text-5xl tracking-normal whitespace-nowrap bg-green-300 rounded-lg border border-green-300 border-solid leading-[52px] min-h-[59px] text-[color:var(--sds-color-text-brand-default)] max-md:ml-2.5 max-md:text-4xl"
      >
        Register
      </a>
    </section>
  );
};

export default Hero;
