/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Hero from "./Hero";
import StatSection from "./StatSection";
import FeatureSection from "./FeatureSection";

const MainContent = () => {
  return (
    <main className="flex overflow-hidden flex-col pb-60 bg-white max-md:pb-24 max-w-[80%] mx-auto">
      <Hero />
      <StatSection />
      <FeatureSection
        title="Sleep and Stress Insights"
        description="Your schedule adapts in real time based on sleep quality and stress levels, shifting tasks to ensure a balance between recovery and productivity."
        imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/19854e0e23b225043edefdcbc91ab96444eb380a434f620d372d0fe3005daeea?placeholderIfAbsent=true&apiKey=be7d969155c74017b8611192d433b602"
        imageAlt="Sleep and Stress Insights Illustration"
      />
      <FeatureSection
        title="Long-Term Goal Integration"
        description="Incorporates your long-term goals into daily planning, ensuring steady progress without overwhelming your routine."
        imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/fa16f07a9e3b0a1949ab3be718ce46506be14f1d171d99b59d7cb12bc8bf7b6b?placeholderIfAbsent=true&apiKey=be7d969155c74017b8611192d433b602"
        imageAlt="Long-Term Goal Integration Illustration"
        reverse={true}
      />
      <FeatureSection
        title="Personalized for You"
        description="Customizes your schedule around your habits and priorities, making sure your day aligns with your personal and professional needs."
        imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/3a3d0482f74b0253b6b269f1e3ef43928a321e1d86d36db465daae7aabf0609a?placeholderIfAbsent=true&apiKey=be7d969155c74017b8611192d433b602"
        imageAlt="Personalized Calendar Illustration"
      />
    </main>
  );
};

export default MainContent;
