/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StatCard from "./StatCard";

const StatSection = () => {
  const stats = [
    {
      content: (
        <>
          Planning your tasks can boost your efficiency{" "}
          <span className="underline">up to 25%!</span>
        </>
      ),
    },
    {
      content: (
        <>
          Writing down your goals boosts your chances of{" "}
          <span className="underline">success by 42%!</span>
        </>
      ),
    },
    {
      content: (
        <>
          Effective task management can help you save{" "}
          <span className="underline">up to 2 hours</span> each day!
        </>
      ),
    },
  ];

  return (
    <section className="self-center mt-32 ml-4 max-w-full w-[1097px] max-md:mt-10">
      <div className="flex gap-5 max-md:flex-col">
        {stats.map((stat, index) => (
          <div
            key={index}
            className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full"
          >
            <StatCard content={stat.content} />
          </div>
        ))}
      </div>
    </section>
  );
};

export default StatSection;
