/**
 * This code was generated by Builder.io.
 */

"use client"; // This makes the entire component a Client Component

import React from "react";
import Header from "../components/Header";
import MainContent from "../components/MainContent";

const App = () => {
  return (
    <>
      <MainContent />
      <style jsx>{`
        builder-component {
          max-width: none !important;
        }
      `}</style>
    </>
  );
};

export default App;
